site_name: Hans_Robo's cheatsheet
theme:
  name: material
extra:
  font:
    text: "Noto Sans JP"
    code: "Consolas"
copyright: "Copyright &copy; 2022 HansRobo"
plugins:
  - search
  - git-revision-date-localized